# Meta Data for SEO

## Homepage
title = "Auth0"
titleSeparator = "-"
titleAddition = "Documentação"
description = ""

## Documentation
# docsVersion = "0.1"

## Open Graph
images = ["logo-4i.png"]
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaName = "Auth0"
schemaAuthor = "Nathalya Stefhany Pereira"
schemaAuthorGitHub = "https://github.com/NathalyaStefhany"
schemaLogo = "logo-41.png"
schemaLinkedIn = "https://br.linkedin.com/company/4intelligence-ai"
schemaGitHub = "https://github.com/4intelligence"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/NathalyaStefhany/Auth0"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
